[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#070A13"
secondaryBackgroundColor = "#0F172A"
textColor = "#F1F5F9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
